### ISSUE TITLE
Implement accurate Luminance transformation function.

### ISSUE THREAD

**Issue by KelSolaar** [campi3d/MARI-Extension-Pack#108]
I will refer to my comment there: http://mari.ideascale.com/a/dtd/MARI-Extension-Pack-2-1/726525-15287

Basically, the [current `Luminance` function](https://github.com/campi3d/MARI-Extension-Pack/blob/master/Scripts/Shaders/FunctionLibrary/JK_FunctionLibrary/ID_ProceduralLib.glslc#L392) is incorrectly computing the *Luminance*, it doesn't account for the visual system sensitivity to wavelength.
This should be done by using different weights that are dependent on your given colourspace specification (specifically the primaries and its whitepoint / illuminant).

Here is the *Luminance* equation for *sRGB* (assuming linear values):

```python
# https://github.com/colour-science/colour/blob/develop/colour/models/derivation.py#L158
 
import colour
 
sRGB = colour.RGB_COLOURSPACES['sRGB']
colour.RGB_luminance_equation(sRGB.primaries, sRGB.whitepoint)
 
# u'Y = 0.212636821677(R) + 0.715182981841(G) + 0.0721801964814(B)'
```

Ideally if you were seeking for accuracy, you would like to have one per potential colourspace.

**Comment by campi3d** [comment]
Hey Thomas,
thanks for that. I only used the luminance function for color temperature node to quickly compute and reapply the original luminance (which it does, otherwise just by applying the node the look of your textures would change without doing anything).

I encourage you to make changes you feel are necessary. We are open source after all for a reason (because non of us are programmers we basically make shit up as we go along so it's good to have this 'community error check' :)

**Comment by campi3d** [comment]
I can add you as a contributor if you want so you have direct access to this git.

**Comment by campi3d** [comment]
Note to self: Check how Mari runs Alpha is Luminance to see what they are doing.

**Comment by KelSolaar** [comment]
Hey Jenz, no worries :)

I don't have Mari with me (my workstation is right now packed in a container somewhere between France and NZ) so I won't be able to do that anytime soon! I will check at work if we have the pack installed, I can probably do it from there.

**Comment by campi3d** [comment]
Hey Thomas (jens with an s btw).

hope you are settling well into the weta TEX team :) I believe they have 2.0 (not sure, they might still have mariScripts pak running which I set up -  ask John Harnagel) . You can always unload the pak from your environment and dump 2.1 into you Mari/Scripts Folder in your home folder. But you got a few months to the next release anyway.

Like I said on ideascale, I've been using a pretty straight up implementation from Tanner Helland
http://www.tannerhelland.com/4435/convert-temperature-rgb-algorithm-code/

That's pretty much the extend of my research I did :) Sorry to disappoint. 

That being said the links you posted are very interesting (wish I had those when working on the node) and the luminance function is absolutely something worth changing since I see that being used more.

If I ever will change the core computation for the color temperature I don't know. It does what I want it do which is make minor adjustments. As you can see from the Issues the list of things I want to do is rather long and I seem to be the only person working on things for the last year. So if you are really interested in a more correct implementation soon you might have to do it yourself or wait a while.

**Comment by KelSolaar** [comment]
Sorry about spelling incorrectly your first name, probably fat fingered the keyboard!

It is going allright for now at Weta, great team and studio :+1: 

No worries about the colour temperature code, I had no real problem with it (hence the fact I did not created an issue), more with the documentation accuracy actually.

The Luminance thing is really easy to do and was worth an issue though :)

The only major benefit I would see from a colorimetrically correct implementation (based on said Robertson (1968) method) is that it would give you access to tint changing (magenta / green in lower portion of colour temperatures) but as you can probably rotate the hue, it is probably not needed.

**Comment by campi3d** [comment]
Just going to answer here instead of ideascale.

I had a quick look at some existing Mari Luminance functions.

There is this 
float lum = dot(vec4(0.2126, 0.7152, 0.0722, 0.0), #Input);

which looks like it is weighting for linear only (?).
Then there is mriRgb2Hsl function which gives you the lightness component  which is different then 
the luminosity one above. Since Mari is internally linear I guess the first one is the one to use.
Since there is no way to get the active color lookup from an opengl node I don't know how to weigh things properly based on the active colorspace to be honest.

As for your question regarding the sRgb Mode in the current ColorTemperature Node:

Kelvin2Rgb returns me a color range based on sRgb weights. I am then linearizing it. As you correctly identified I am multing the result from Kelvin2Rgb against the original, then reapplying the original luminance. 

The sRgb mode simply determines what is multed against the original: The original sRGB result or the linearized one (sRGb off). 

Not every one is using linear Inputs in Mari (weta sure as hell isn't) so if you are in a pure sRGB colorspace in Mari the resulting color tint would look quite a lot different. 
I might have to word the documentation a bit better in that regard.

**Comment by KelSolaar** [comment]
> There is this 
> float lum = dot(vec4(0.2126, 0.7152, 0.0722, 0.0), #Input);
> 
> which looks like it is weighting for linear only (?).

Yes those are the *Luminance* weights for *sRGB* / *Rec. 709* colourspaces using linear values and is the one to use in your computations.

The weighted sum of non-linear components (with the OECF / gamma correction applied) is called *luma*: http://www.poynton.com/notes/colour_and_gamma/ColorFAQ.html#RTFToC11

> Then there is mriRgb2Hsl function which gives you the lightness component which is different then 
the luminosity one above.

You should avoid using the brightness / value / lightness computed by HSL / HSV colourspaces it is not accounting for visual system sensitivity and is highly non linear: http://www.poynton.com/notes/colour_and_gamma/GammaFAQ.html#HSI 

> I don't know how to weigh things properly based on the active colorspace to be honest.

I don't think it will change a lot the result in practical cases, I haven't done proper colour difference computations but I don't think you will see a massive difference if you end up using the wrong one for a given RGB colourspace.

**Comment by campi3d** [comment]
Ok, I'll update the function. Thanks for the help ! And the offer still stands. If you want to help out or contribute anything (no matter the extend or length of your involvement) you are highly welcome !

**Comment by campi3d** [comment]
Hmm. I updated the function but something seems off.
Meaning that just by applying the new way the color temperature is changing the look of the textures (although very slightly) even when using the original luminance. Will need to take a closer look at this.

**Comment by KelSolaar** [comment]
Nice! Guess this is a closed issue then :)
