### ISSUE TITLE
Icons not found if several path in USER_SCRIPTS environment variable

### ISSUE THREAD

**Issue by Regnareb** [campi3d/MARI-Extension-Pack#109]
If you have more than one path in the mari.resources.USER_SCRIPTS environment variable, it won't find the path to the icons because it is invalid.

Actually you should never use absolute path, relative is the way to go. And btw the real path should be mari.resources.ICONS instead of mari.resources.USER_SCRIPTS.

**Comment by Regnareb** [comment]
And you should never *ever* put a specific OS separator in the path of files. 
Let Python do this automatically with [os.path.join](https://docs.python.org/2/library/os.path.html#os.path.join)

**Comment by campi3d** [comment]
I can't put anything in the icons folder in the mari installation since we don't have an installer and people are not reading the installation help as it is :)

I thought I had dealt with the multiple path issues in the __initExtensionPack__ file where it searches through all paths in the user script env variable to find where the extension pack is sitting.
I need to check if I am passing that information to the tools_menu.py file. Maybe I don't.

Totally agreed that OS specific operators are a no go. I probably just put it in to test it and forgot about it (and since we did test on windows, mac and linux it never came up again).

Anything you find and feel like changing please do and do pull requests. Since I am hardly a seasoned python dev it will help everyone.

**Comment by campi3d** [comment]
I've created a new issue for the hierarchy stuff you suggested: 
https://github.com/campi3d/MARI-Extension-Pack/issues/112

Let's discuss that stuff there.

**Comment by campi3d** [comment]
I've made some changes here: https://github.com/campi3d/MARI-Extension-Pack/commit/f33b4bf5a52160ed138da88ed6665ca7c9708094 if you want to take a quick look.

Is there anythign else (for example in _initExtensionpack.py__ that are an issue for you guys ?

**Comment by campi3d** [comment]
Seems to work.
