### ISSUE TITLE
merging and converting layers to paintable causes channels to go grey

### ISSUE THREAD

**Issue by ttanimura** [campi3d/MARI-Extension-Pack#114]
merging layers or converting them to paintable causes channels to go grey using extension pack 2.1... the issue does not occur in 2.0

**Comment by campi3d** [comment]
What Mari version are you using ?

**Comment by campi3d** [comment]
Also when you say merging layers - do you mean using 'Merge Layers' or 'Clone & Merge' ?

**Comment by ttanimura** [comment]
we are using mari 2.6v3, and its happening when using 'merge layers' and 'convert to paintable'. thanks!

**Comment by campi3d** [comment]
I haven't touched 'merge layers'. It's a vanilla Mari function.So that one can't be me.
What OS are you on ? 

I have modified ConvertToPaintable to run with the viewport off. 
If you comment out

https://github.com/campi3d/MARI-Extension-Pack/blob/master/Scripts/Tools/Layers/extPack_convert_to_paintable.py#L268-270

and

https://github.com/campi3d/MARI-Extension-Pack/blob/master/Scripts/Tools/Layers/extPack_convert_to_paintable.py#L304

and it still doesn't work then this isn't me ...

**Comment by ttanimura** [comment]
ok i will try. the user reported the problem right after we switched to 2.1. when we reverted back to extension pack 2.0 her problem went away.

**Comment by campi3d** [comment]
If you could try again as is that would be great. I wouldn't put it past Mari to glitch like that.

If it happens with Channel Layers (shared channels into another channel) there also have been some modifications to convertToPaintable regarding that. But again, the regular 'Merge' is untouched.

I definitely can't repro it on my windows machine in front of me atm, so if it turns out t be clearly ExtPack2.1 related any info I can get (screenshot of layer palette at the time for example) will help.

**Comment by campi3d** [comment]
Where are we at with that ? Still a problem ? 
If not: Did it go away on it's own (-> Mari glitch) or did it go away after removing the vieportOff trigger

**Comment by ttanimura** [comment]
sorry, meant to reply to this earlier but got distracted... it appears that it went away by itself. thanks for checking in!
